package agent

import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/brown-enterprises/be-code/internal/discover"
	"github.com/brown-enterprises/be-code/internal/provider"
)

// harnessWords flags mentions of the harness itself rather than the
// project. "compat" and "read_file" are deliberately excluded: they
// false-positive on ordinary prose ("backward compatibility", a project's
// own read_file helper).
var harnessWords = []string{"be-code", "tool_call", "write_file", "edit_file", "verification loop", "agent loop", "system prompt"}

// commandSpan finds backtick-quoted spans anywhere in a line (not just at
// line start, since generated prose usually leads with prose before the
// code span, e.g. "Build with `go build ./...`").
var commandSpan = regexp.MustCompile("`([^`\n]+)`")

// fencedBlock finds fenced code blocks (```...```), which get their own
// scan since a single-backtick span never sees inside them.
var fencedBlock = regexp.MustCompile("(?s)```[a-zA-Z0-9]*\n(.*?)```")

// commandVerb recognizes the runners whose invocations must match a
// measured command exactly.
var commandVerb = regexp.MustCompile(`^(go|npm|npx|python3?|pytest|cargo|make)\b`)

// extractCommands collects every runner invocation the doc claims: inline
// backtick spans, lines inside fenced code blocks, and bare lines whose
// first token is a runner verb.
func extractCommands(doc string) []string {
	var cmds []string
	for _, m := range fencedBlock.FindAllStringSubmatch(doc, -1) {
		for _, line := range strings.Split(m[1], "\n") {
			line = strings.TrimSpace(line)
			if commandVerb.MatchString(line) {
				cmds = append(cmds, line)
			}
		}
	}
	rest := fencedBlock.ReplaceAllString(doc, "")
	for _, m := range commandSpan.FindAllStringSubmatch(rest, -1) {
		cmd := strings.TrimSpace(m[1])
		if commandVerb.MatchString(cmd) {
			cmds = append(cmds, cmd)
		}
	}
	for _, line := range strings.Split(rest, "\n") {
		line = strings.TrimSpace(strings.Trim(strings.TrimSpace(line), "`"))
		if commandVerb.MatchString(line) {
			cmds = append(cmds, line)
		}
	}
	return cmds
}

// ValidateProjectNotes returns the reasons a generated BECODE.md must be
// rejected; empty means acceptable.
func ValidateProjectNotes(doc string, facts discover.Facts) []string {
	var v []string
	low := strings.ToLower(doc)
	for _, w := range harnessWords {
		if strings.Contains(low, w) {
			v = append(v, fmt.Sprintf("it describes the tool (%q)", w))
		}
	}
	cited := 0
	for _, n := range facts.Names() {
		if strings.Contains(doc, n) {
			cited++
		}
	}
	if cited < 2 {
		v = append(v, "it cites fewer than two measured files, directories or commands")
	}
	known := strings.Join(facts.Names(), "\n")
	seen := map[string]bool{}
	for _, cmd := range extractCommands(doc) {
		if seen[cmd] {
			continue
		}
		seen[cmd] = true
		if !strings.Contains(known, cmd) {
			v = append(v, fmt.Sprintf("command %q is not in the measured facts", cmd))
		}
	}
	if strings.Count(strings.TrimSpace(doc), "\n")+1 > 150 {
		v = append(v, "it is longer than 150 lines")
	}
	return v
}

// InitProject asks the model for BECODE.md prose from the facts, validates
// it, retries once with the violations, and falls back to the fact sheet.
func (a *Agent) InitProject(ctx context.Context, facts discover.Facts) (string, bool, error) {
	user := "Facts:\n\n" + facts.Markdown()
	var last []string
	var lastDoc string
	for attempt := 0; attempt < 2; attempt++ {
		msgs := []provider.Message{{Role: provider.RoleSystem, Content: InitFrame}, {Role: provider.RoleUser, Content: user}}
		if attempt == 1 {
			msgs = append(msgs,
				provider.Message{Role: provider.RoleAssistant, Content: lastDoc},
				provider.Message{Role: provider.RoleUser, Content: "The previous attempt was rejected because: " + strings.Join(last, "; ") + ". Write BECODE.md again, correcting these."})
		}
		resp, err := a.Provider.Chat(ctx, provider.ChatRequest{Model: a.Model, Messages: msgs, Temperature: 0.2, NoThink: true}, nil)
		if err != nil {
			return "", false, err
		}
		doc := resp.Content
		if a.Profile.StripThink {
			doc = StripThink(doc)
		}
		doc = strings.TrimSpace(doc) + "\n"
		last = ValidateProjectNotes(doc, facts)
		if len(last) == 0 {
			return doc, false, nil
		}
		lastDoc = doc
	}
	fallback := fmt.Sprintf("<!-- generated by be-code init from measured facts; the model's overview was rejected: %s -->\n\n%s", strings.Join(last, "; "), facts.Markdown())
	return fallback, true, nil
}
